name=input("Enter Student Name:")
roll_no=input("Enter Roll Number:")
age=input("Enter Age:")
math_marks=input("Enter Math marks:")
sci_marks=input("Enter Science marks:")
eng_marks=input("Enter English marks:")
print("Name:",name)
print("Roll Number:",roll_no)
print("Age:",age)
print("Math:",math_marks)
print("Science:",sci_marks)
print("English:",eng_marks)
print("Total:",math_marks+sci_marks+eng_marks,"/300")
print("Average:",math_marks+sci_marks+eng_marks/3)
print("Percentage:",math_marks+sci_marks+eng_marks/300*100)