birth_year=int(input("Enter Birth Year:"))
height_in_cm=float(input("Enter Height (in cm):"))
vip_pass=bool(int(input("Have a VIP Pass? (1 for Yes, 0 for No):")))
print("Age:",2026-birth_year)
print("Height (meters):",height_in_cm/100)
print("Can Enter Park:",2026-birth_year>12)
print("Needs Child Ticket:",12<=2026-birth_year<18)
print("Needs Adult Ticket:",2026-birth_year>=18)
print("Can Ride Water Slide:",2026-birth_year>12 and height_in_cm/100>1.4)
print("Gets VIP Access:",2026-birth_year>=18 and vip_pass==1)