sen=input("Enter a sentance:")
pos=int(input("Enter position for indexing:"))
print("Character at position",pos,":","'",sen[pos],"'")
start=int(input("Enter start index for slicing:"))
end=int(input("Enter end index for slicing:"))
print("Sliced string [",start,":",end,"]:'",sen[start:end],"'")
print("Uppercase:",sen.upper())
print("Lowercase:",sen.lower())
replace=input("Enter word to replace:")
replacement=input("Enter replacement word:")
print("After replace:",sen.replace(replace,replacement))
print("Length of sentance:",len(sen))